think this works
rapyuta-robotics/rosmon pull request #3
Opened 2019-04-19 07:54 UTC by Vuwij

2019-04-20 12:01 UTC, gauthamm commented on src/monitor/monitor.cpp
> +		} catch (const boost::filesystem::filesystem_error& ex) {
why wrap everything on try? Just wrap only the call that can throw the error and continue.

2019-05-10 06:00 UTC, gauthamm commented on src/monitor/monitor.cpp
> +        fs::path statPath;
formatting

2019-05-10 06:00 UTC, gauthamm commented on src/monitor/monitor.cpp
> +				continue;
wrap in braces

2019-05-10 07:08 UTC, alankritapathak approved these changes

2019-05-10 07:11 UTC, gauthamm approved these changes

2019-05-10 07:16 UTC, abolinsky approved these changes

2019-05-10 07:18 UTC, abolinsky requested changes

2019-05-10 07:18 UTC, abolinsky commented on src/monitor/monitor.cpp
> +				continue;
please always use braces to mark scope.

2019-05-10 07:20 UTC, abolinsky approved these changes

2019-05-13 11:15 UTC, merged